# Generated by Django 3.2.11 on 2022-03-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='total_distance',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='metadata',
            name='total_locations',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='metadata',
            name='total_time',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
