# Generated by Django 3.2.11 on 2022-04-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220327_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='total_distance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='total_hours',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
