# Generated by Django 3.2.11 on 2022-04-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220331_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='average_speed',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
