# Generated by Django 3.2.11 on 2022-04-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_track_average_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='total_time_saved',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
