# Generated by Django 3.2.11 on 2022-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_metadata_total_time_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='total_time_saved',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
