# Generated by Django 3.2.11 on 2022-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_track_total_time_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='processed_csv',
            field=models.FileField(blank=True, upload_to='processed/'),
        ),
    ]
