# Generated by Django 3.2.11 on 2022-04-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_track_processed_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='zip_file',
            field=models.FileField(blank=True, upload_to='processed/'),
        ),
    ]
